version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
after_build:
- cmd: 7z a SC2_GameTranslater.zip %APPVEYOR_BUILD_FOLDER%\SC2_GameTranslater\bin\Release\*.dll -i!%APPVEYOR_BUILD_FOLDER%\SC2_GameTranslater\bin\Release\*.exe
artifacts:
- path: SC2_GameTranslater.zip
  name: SC2_GameTranslater
deploy:
  tag: SC2_GameTranslater-v$(appveyor_build_version)
  release: SC2_GameTranslater-v$(appveyor_build_version)
  description: 'SC2_GameTranslater Draft'
  provider: GitHub
  auth_token:
    secure: d6AlNpEw9QfBhGZIJ23uMczwHMuj99zFcQBwSgyX4CGrF7/zPZ1DaDYJwsWgV5kb
  artifact: SC2_GameTranslater
  prerelease: true
  force_update: true
  on:
    branch: master
    APPVEYOR_REPO_TAG: true 